version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/grocerydb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=AdminRandom123

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: grocerydb
      MYSQL_ROOT_PASSWORD: AdminRandom123
    ports:
      - "3306:3306"